// A small library of ready-to-use starting points — every node type here
// is a real, already-verified business-logic node (see
// whatsapp-flow-engine.service.ts), not admin-authored placeholder text.
// Picking one just creates a normal editable flow pre-populated with this
// definition; nothing about it is special afterward — same edit/save/
// activate/preview flow as anything built by hand or generated by AI.

export interface FlowTemplate {
  key: string;
  name: string;
  description: string;
  definition: { nodes: unknown[]; edges: unknown[] };
}

const n = (id: string, type: string, x: number, y: number, data: Record<string, unknown> = {}) => ({
  id, type, position: { x, y }, data,
});
const e = (id: string, source: string, target: string, sourceHandle?: string) => ({
  id, source, target, sourceHandle: sourceHandle ?? null,
});

export const FLOW_TEMPLATES: FlowTemplate[] = [
  {
    key: 'main-menu',
    name: 'Main Menu — Order Medicine / Status / Doctor',
    description:
      'The full front door: a "how can I help?" menu branching into the real prescription-marketplace, order/booking status, and doctor-booking pipelines. The most complete starting point — good default for most tenants.',
    definition: {
      nodes: [
        n('start', 'start', 0, 0),
        n('menu', 'buttons', 0, 100, {
          text: 'Hi! 👋 Welcome to ZyroHealth. How can I help you today?',
          // WhatsApp hard-caps quick-reply button titles at 20 characters
          // and truncates silently (no ellipsis) past that — keep every
          // label here at 20 chars or under.
          options: [
            { id: 'order_medicine', label: 'Order Medicine' },
            { id: 'check_status', label: 'Check Status' },
            { id: 'talk_doctor', label: 'Talk to a Doctor' },
          ],
        }),
        n('upload', 'upload_prescription', -300, 250),
        n('await_quotes', 'await_shop_quotes', -300, 350),
        n('select_quote', 'select_quote', -300, 450),
        n('order_payment', 'order_payment', -300, 550),
        n('track_delivery', 'track_delivery', -300, 650),
        n('end_order', 'end', -300, 750),
        n('order_status', 'platform_order_status', 0, 250),
        n('manage_booking', 'platform_manage_booking', 0, 350),
        n('end_status', 'end', 0, 450),
        n('specialty_list', 'platform_specialty_list', 300, 250),
        n('doctor_list', 'platform_doctor_list', 300, 350),
        n('slot_list', 'platform_slot_list', 300, 450),
        n('consultation_type', 'platform_consultation_type', 300, 550),
        n('payment_method', 'platform_payment_method', 300, 650),
        n('create_booking', 'platform_create_booking', 300, 750),
        n('end_booking', 'end', 300, 850),
      ],
      edges: [
        e('e1', 'start', 'menu'),
        e('e2', 'menu', 'upload', 'order_medicine'),
        e('e3', 'menu', 'order_status', 'check_status'),
        e('e4', 'menu', 'specialty_list', 'talk_doctor'),
        e('e5', 'upload', 'await_quotes'),
        e('e6', 'await_quotes', 'select_quote'),
        e('e7', 'select_quote', 'order_payment'),
        e('e8', 'order_payment', 'track_delivery'),
        e('e9', 'track_delivery', 'end_order'),
        e('e10', 'order_status', 'manage_booking'),
        e('e11', 'manage_booking', 'end_status', 'cancel'),
        e('e12', 'manage_booking', 'end_status', 'keep'),
        e('e13', 'manage_booking', 'slot_list', 'reschedule'),
        e('e14', 'specialty_list', 'doctor_list'),
        e('e15', 'doctor_list', 'slot_list'),
        e('e16', 'slot_list', 'consultation_type'),
        e('e17', 'consultation_type', 'payment_method'),
        e('e18', 'payment_method', 'create_booking'),
        e('e19', 'create_booking', 'end_booking'),
        e('e20', 'create_booking', 'manage_booking', 'conflict'),
      ],
    },
  },
  {
    key: 'book-doctor-only',
    name: 'Book a Doctor (Only)',
    description:
      'Just the doctor-booking pipeline, no menu — greets, then straight into specialty → doctor → slot → consultation type → payment → real booking. Good for a tenant that only offers consultations, not a pharmacy.',
    definition: {
      nodes: [
        n('start', 'start', 0, 0),
        n('greet', 'message', 0, 100, { text: 'Hi! 👋 Let\'s get you booked in with a doctor.' }),
        n('specialty_list', 'platform_specialty_list', 0, 200),
        n('doctor_list', 'platform_doctor_list', 0, 300),
        n('slot_list', 'platform_slot_list', 0, 400),
        n('consultation_type', 'platform_consultation_type', 0, 500),
        n('payment_method', 'platform_payment_method', 0, 600),
        n('create_booking', 'platform_create_booking', 0, 700),
        n('end_booking', 'end', 0, 800),
      ],
      edges: [
        e('e1', 'start', 'greet'),
        e('e2', 'greet', 'specialty_list'),
        e('e3', 'specialty_list', 'doctor_list'),
        e('e4', 'doctor_list', 'slot_list'),
        e('e5', 'slot_list', 'consultation_type'),
        e('e6', 'consultation_type', 'payment_method'),
        e('e7', 'payment_method', 'create_booking'),
        e('e8', 'create_booking', 'end_booking'),
      ],
    },
  },
  {
    key: 'order-medicine-only',
    name: 'Order Medicine (Only)',
    description:
      'Just the prescription marketplace, no menu — greets, asks for a prescription photo, waits for a pharmacy quote, lets the patient pick one, collects delivery/payment, then tracks delivery. Good for a pharmacy-only tenant.',
    definition: {
      nodes: [
        n('start', 'start', 0, 0),
        n('greet', 'message', 0, 100, { text: 'Hi! 👋 Send a photo of your prescription and we\'ll get you a quote.' }),
        n('upload', 'upload_prescription', 0, 200),
        n('await_quotes', 'await_shop_quotes', 0, 300),
        n('select_quote', 'select_quote', 0, 400),
        n('order_payment', 'order_payment', 0, 500),
        n('track_delivery', 'track_delivery', 0, 600),
        n('end_order', 'end', 0, 700),
      ],
      edges: [
        e('e1', 'start', 'greet'),
        e('e2', 'greet', 'upload'),
        e('e3', 'upload', 'await_quotes'),
        e('e4', 'await_quotes', 'select_quote'),
        e('e5', 'select_quote', 'order_payment'),
        e('e6', 'order_payment', 'track_delivery'),
        e('e7', 'track_delivery', 'end_order'),
      ],
    },
  },
  {
    key: 'booking-with-manage',
    name: 'Book a Doctor + Manage (Cancel/Reschedule)',
    description:
      'A menu offering "Book an Appointment" or "Manage My Booking" up front, plus automatic cancel/reschedule offers if a booking attempt conflicts with one they already have — the self-service angle in one place.',
    definition: {
      nodes: [
        n('start', 'start', 0, 0),
        n('menu', 'buttons', 0, 100, {
          text: 'Hi! 👋 Would you like to book a new appointment, or manage an existing one?',
          options: [
            { id: 'book', label: 'Book an Appointment' },
            { id: 'manage', label: 'Manage My Booking' },
          ],
        }),
        n('specialty_list', 'platform_specialty_list', -200, 250),
        n('doctor_list', 'platform_doctor_list', -200, 350),
        n('slot_list', 'platform_slot_list', -200, 450),
        n('consultation_type', 'platform_consultation_type', -200, 550),
        n('payment_method', 'platform_payment_method', -200, 650),
        n('create_booking', 'platform_create_booking', -200, 750),
        n('end_booking', 'end', -200, 850),
        n('manage_booking', 'platform_manage_booking', 200, 250),
      ],
      edges: [
        e('e1', 'start', 'menu'),
        e('e2', 'menu', 'specialty_list', 'book'),
        e('e3', 'menu', 'manage_booking', 'manage'),
        e('e4', 'specialty_list', 'doctor_list'),
        e('e5', 'doctor_list', 'slot_list'),
        e('e6', 'slot_list', 'consultation_type'),
        e('e7', 'consultation_type', 'payment_method'),
        e('e8', 'payment_method', 'create_booking'),
        e('e9', 'create_booking', 'end_booking'),
        e('e10', 'create_booking', 'manage_booking', 'conflict'),
        e('e11', 'manage_booking', 'end_booking', 'cancel'),
        e('e12', 'manage_booking', 'end_booking', 'keep'),
        e('e13', 'manage_booking', 'slot_list', 'reschedule'),
      ],
    },
  },
  {
    key: 'ai-assistant-handoff',
    name: 'AI Symptom Assistant + Human Handoff',
    description:
      'A menu offering an open-ended AI chat for symptom questions, or a direct handoff to a real staff member — good for a support-first tenant that wants an always-on assistant with an easy escape hatch to a human.',
    definition: {
      nodes: [
        n('start', 'start', 0, 0),
        n('menu', 'buttons', 0, 100, {
          text: 'Hi! 👋 How can I help — ask me a health question, or would you rather talk to our team?',
          options: [
            { id: 'ask_ai', label: 'Ask a Question' },
            { id: 'talk_support', label: 'Talk to Support' },
          ],
        }),
        n('ai_chat', 'ai', -150, 250, {
          systemPrompt:
            'You are a careful, empathetic ZyroHealth assistant helping a patient describe their symptoms. Keep replies short and clear. Never diagnose — suggest booking a doctor for anything serious. If it sounds like an emergency, tell them to seek immediate care.',
        }),
        n('support_handoff', 'handoff', 150, 250, {
          text: 'Got it — connecting you with our support team now, they\'ll reply here shortly. 🙏',
        }),
      ],
      edges: [
        e('e1', 'start', 'menu'),
        e('e2', 'menu', 'ai_chat', 'ask_ai'),
        e('e3', 'menu', 'support_handoff', 'talk_support'),
      ],
    },
  },
];
